services:
  frontend:
    build:
      context: ./frontend
      target: dev
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:5173"

  backend:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - pdf_uploads:/app/uploads
