services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    user: "0:0"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - pdf_uploads:/app/uploads

volumes:
  pdf_uploads:
